import tkinter as tk
from tkinter import *
import time as t

root = tk.Tk()
root.title('Coder and Decoder')
root.geometry('600x500')
root.clipboard_append('Label')
root.resizable(True ,True)

for i in range (5):
    for j in range (2):
        root.columnconfigure(j, weight=1)
        root.rowconfigure(i, weight=1)

def hide_label():
    sucsesful_copy['text']=''

def code():
    coder = ent.get()
    # ру
    coder = coder.replace('а','Х')
    coder = coder.replace('б','@')
    coder = coder.replace('в','#')
    coder = coder.replace('г','$')
    coder = coder.replace('е','^')
    coder = coder.replace('ё','&')
    coder = coder.replace('ж','*')
    coder = coder.replace('д','%')
    coder = coder.replace('з','[')
    coder = coder.replace('и',']')
    coder = coder.replace('й',"'")
    coder = coder.replace('к','"')
    coder = coder.replace('л','~')
    coder = coder.replace('м','+')
    coder = coder.replace('н','_')
    coder = coder.replace('о','-')
    coder = coder.replace('п','=')
    coder = coder.replace('р','(')
    coder = coder.replace('с',')')
    coder = coder.replace('т','•')
    coder = coder.replace('у','|')
    coder = coder.replace('ф','/')
    coder = coder.replace('х','>')
    coder = coder.replace('ц','<')
    coder = coder.replace('ч',':')
    coder = coder.replace('щ',';')
    coder = coder.replace('ш','^')
    coder = coder.replace('ъ','?')
    coder = coder.replace('ы','.')
    coder = coder.replace('ь',',')
    coder = coder.replace('э','{')
    coder = coder.replace('ю','№')
    coder = coder.replace('я','}')
    # англ
    coder = coder.replace('a','Х')
    coder = coder.replace('b','@')
    coder = coder.replace('c','#')
    coder = coder.replace('d','$')
    coder = coder.replace('e','^')
    coder = coder.replace('f','&')
    coder = coder.replace('g','*')
    coder = coder.replace('h','%')
    coder = coder.replace('i','[')
    coder = coder.replace('j',']')
    coder = coder.replace('k',"'")
    coder = coder.replace('l','"')
    coder = coder.replace('m','~')
    coder = coder.replace('n','+')
    coder = coder.replace('o','_')
    coder = coder.replace('p','-')
    coder = coder.replace('q','=')
    coder = coder.replace('r','(')
    coder = coder.replace('s',')')
    coder = coder.replace('t','•')
    coder = coder.replace('u','|')
    coder = coder.replace('v','/')
    coder = coder.replace('w','>')
    coder = coder.replace('x','<')
    coder = coder.replace('y',':')
    coder = coder.replace('z',';')
    txt.config(text=coder)
    root.clipboard_clear()  # Очистить буфер обмена
    root.clipboard_append(txt['text'])
    sucsesful_copy['text'] = 'Sucsesfuly copied!'
    sucsesful_copy.after(1000, hide_label)

def decode():
    decoder = ent2.get()
    eng_decoder = decoder
    decoder = decoder.replace('Х','а')
    decoder = decoder.replace('@','б')
    decoder = decoder.replace('#','в')
    decoder = decoder.replace('$','г')
    decoder = decoder.replace('^','е')
    decoder = decoder.replace('&','ё')
    decoder = decoder.replace('*','ж')
    decoder = decoder.replace('%','д')
    decoder = decoder.replace('[','з')
    decoder = decoder.replace(']','и')
    decoder = decoder.replace("'","й")
    decoder = decoder.replace('"','к')
    decoder = decoder.replace('~','л')
    decoder = decoder.replace('+','м')
    decoder = decoder.replace('_','н')
    decoder = decoder.replace('-','о')
    decoder = decoder.replace('=','п')
    decoder = decoder.replace('(','р')
    decoder = decoder.replace(')','с')
    decoder = decoder.replace('•','т')
    decoder = decoder.replace('|','у')
    decoder = decoder.replace('/','ф')
    decoder = decoder.replace('>','х')
    decoder = decoder.replace('<','ц')
    decoder = decoder.replace(':','ч')
    decoder = decoder.replace(';','щ')
    decoder = decoder.replace('^','ш')
    decoder = decoder.replace('?','ъ')
    decoder = decoder.replace('.','ы')
    decoder = decoder.replace(',','ь')
    decoder = decoder.replace('{','э')
    decoder = decoder.replace('№','ю')
    decoder = decoder.replace('}','я')
    # eng
    eng_decoder = eng_decoder.replace('Х','a')
    eng_decoder = eng_decoder.replace('@','b')
    eng_decoder = eng_decoder.replace('#','c')
    eng_decoder = eng_decoder.replace('$','d')
    eng_decoder = eng_decoder.replace('^','e')
    eng_decoder = eng_decoder.replace('&','f')
    eng_decoder = eng_decoder.replace('*','g')
    eng_decoder = eng_decoder.replace('%','h')
    eng_decoder = eng_decoder.replace('[','i')
    eng_decoder = eng_decoder.replace(']','j')
    eng_decoder = eng_decoder.replace("'","k")
    eng_decoder = eng_decoder.replace('"','l')
    eng_decoder = eng_decoder.replace('~','m')
    eng_decoder = eng_decoder.replace('+','n')
    eng_decoder = eng_decoder.replace('_','o')
    eng_decoder = eng_decoder.replace('-','p')
    eng_decoder = eng_decoder.replace('=','q')
    eng_decoder = eng_decoder.replace('(','r')
    eng_decoder = eng_decoder.replace(')','s')
    eng_decoder = eng_decoder.replace('•','t')
    eng_decoder = eng_decoder.replace('|','u')
    eng_decoder = eng_decoder.replace('/','v')
    eng_decoder = eng_decoder.replace('>','w')
    eng_decoder = eng_decoder.replace('<','x')
    eng_decoder = eng_decoder.replace(':','y')
    eng_decoder = eng_decoder.replace(';','z')
    txt2.config(text=f'{decoder} / {eng_decoder}')
    sucsesful_copy['text'] = 'Sucsesfuly copied!'
    sucsesful_copy.after(1000, hide_label)
    return decoder

txt = tk.Label(text='code text:', font=('Impact', 20))
txt.grid(row=0,column=0, sticky='nsew')

txt2 = tk.Label(text='decode text:', font=('Impact', 20))
txt2.grid(row=0,column=1, sticky='nsew')

ent = tk.Entry()
ent.grid(row=1,column=0, sticky='nsew', padx=10, pady=10)

ent2 = tk.Entry()
ent2.grid(row=1,column=1, sticky='nsew', padx=10, pady=10)

ex = tk.Button(text='code', command=code)
ex.grid(row=2,column=0, sticky='nsew', padx=10, pady=10)

ex2 = tk.Button(text='decode', command=decode)
ex2.grid(row=2,column=1, sticky='nsew', padx=10, pady=10)

disp_img = Label()
disp_img.grid(row=3,column=0,columnspan=2)

sucsesful_copy = tk.Label(text='', font=('Impact', 20))
sucsesful_copy.grid(row=4,column=0,columnspan=2)

root.mainloop()
